export const screenLabels: Record<string, string> = {
  ACT_VSL_MONITOR: "ACT Vessel Monitor",
  DCT_VSL_MONITOR: "DCT Vessel Monitor",
  ACT_EQU_MONITOR: "ACT EQU MONITOR",
  DCT_EQU_MONITOR: "DCT EQU MONITOR",
  ACT_YARD_MONITOR: "ACT Yard Monitor",
  DCT_YARD_MONITOR: "DCT Yard Monitor",
  ACT_YT_TRACKER: "ACT YT Tracker",
  DCT_YT_TRACKER: "DCT YT Tracker",
  ACT_DASHBOARD: "ACT Dashboard",
  DCT_DASHBOARD: "DCT Dashboard",
  ACT_GATE_MONITOR: "ACT Gate Monitor",
  DCT_GATE_MONITOR: "DCT Gate Monitor",
  ACT_BERTH_MONITOR: "ACT Berth Monitor",
  DCT_BERTH_MONITOR: "DCT Berth Monitor",
  ACT_HEATMAP: "ACT Yard Heatmap",
  DCT_HEATMAP: "DCT Yard Heatmap",
  ACT_YT_TRAIL: "ACT YT Trail",
  DCT_YT_TRAIL: "DCT YT Trail",
  ACT_CRANE_TREND: "ACT Crane Trend",
  DCT_CRANE_TREND: "DCT Crane Trend",
};
