"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useRef } from "react";
import * as THREE from "three";

function Beacon({ position, color }: { position: [number, number, number]; color: string }) { const ref = useRef<THREE.Mesh>(null); useFrame(({ clock }) => { if (ref.current) ref.current.scale.setScalar(.7 + Math.sin(clock.getElapsedTime() * 4) * .25); }); return <mesh ref={ref} position={position}><sphereGeometry args={[.1, 12, 12]} /><meshBasicMaterial color={color} toneMapped={false} /></mesh>; }
function Crane({ x, active = true }: { x: number; active?: boolean }) { const color = active ? "#43f4ff" : "#ff557e"; return <group position={[x, 0, -.8]}><mesh position={[0, 1.2, 0]} rotation={[0, 0, -.08]}><boxGeometry args={[.13, 2.5, .13]} /><meshStandardMaterial color="#9d65ff" emissive="#34156e" emissiveIntensity={1} metalness={.7} roughness={.25} /></mesh><mesh position={[.35, 2.25, 0]}><boxGeometry args={[1.2, .09, .09]} /><meshStandardMaterial color={color} emissive={color} emissiveIntensity={1.2} /></mesh><mesh position={[-.2, 1.15, 0]} rotation={[0, 0, .5]}><boxGeometry args={[.1, 2.2, .1]} /><meshStandardMaterial color="#ff2db7" emissive="#8e0964" emissiveIntensity={1} /></mesh><Beacon position={[.68, 1.72, 0]} color={color} /><mesh position={[.68, 1.48, 0]}><boxGeometry args={[.26, .26, .26]} /><meshBasicMaterial color={color} toneMapped={false} /></mesh></group>; }
function HarborModel() { const vesselRef = useRef<THREE.Group>(null); useFrame(({ clock }) => { if (vesselRef.current) vesselRef.current.position.y = Math.sin(clock.getElapsedTime() * .7) * .03; }); return <><ambientLight intensity={.5} /><directionalLight position={[4, 7, 5]} intensity={1.5} color="#b9b0ff" /><pointLight position={[0, 2.5, 1]} intensity={5} distance={8} color="#ff2db7" /><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -.14, 0]}><planeGeometry args={[14, 8]} /><meshStandardMaterial color="#09051b" metalness={.6} roughness={.5} /></mesh><gridHelper args={[14, 28, "#ff2db7", "#241253"]} position={[0, -.12, 0]} /><group ref={vesselRef}><mesh position={[0, .1, .55]}><boxGeometry args={[4.2, .28, 1.15]} /><meshStandardMaterial color="#160e35" emissive="#0b0620" emissiveIntensity={1} metalness={.7} roughness={.25} /></mesh>{[-1.45, -.72, 0, .72, 1.45].map((x, i) => <mesh key={x} position={[x, .38 + (i % 2) * .18, .55]}><boxGeometry args={[.62, .32, .82]} /><meshStandardMaterial color={["#6d7bff", "#43f4ff", "#ff2db7", "#5dffb0"][i % 4]} emissive={["#202879", "#087f8d", "#8e0964", "#087342"][i % 4]} emissiveIntensity={1.3} /></mesh>)}</group><Crane x={-3.5} /><Crane x={-2.1} /><Crane x={2.5} active={false} /><Crane x={3.8} /></>; }
export function HarborScene({ className = "" }: { className?: string }) { return <div className={`absolute inset-0 pointer-events-none ${className}`} aria-hidden="true"><Canvas camera={{ position: [0, 3.2, 6.2], fov: 38 }} dpr={[1, 1.5]}><color attach="background" args={["#05030d"]} /><HarborModel /><OrbitControls enableZoom={false} enablePan={false} autoRotate autoRotateSpeed={.32} maxPolarAngle={Math.PI / 2.05} minPolarAngle={Math.PI / 3.5} /></Canvas></div>; }
export default HarborScene;
