"use client";

import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/context/auth";
import { SCREEN_LABELS, screenTerminal, getUserScreens } from "@/lib/screens";
import type { ScreenKey } from "@/lib/types";

export function Topbar({ activeScreen, onNavigate }: { activeScreen: ScreenKey | null; onNavigate: (s: ScreenKey) => void }) {
  const { user, login, logout } = useAuth();
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [loginError, setLoginError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [clock, setClock] = useState(() => new Date());
  useEffect(() => { const id = setInterval(() => setClock(new Date()), 1000); return () => clearInterval(id); }, []);
  const myScreens = useMemo<ScreenKey[]>(() => getUserScreens(user), [user]);
  const terminals = useMemo(() => { const values = new Set<string>(); myScreens.forEach((key) => { const terminal = screenTerminal(key); if (terminal) values.add(terminal); }); return ["ACT", "DCT"].filter((terminal) => values.has(terminal)); }, [myScreens]);
  const activeTerm = activeScreen ? (screenTerminal(activeScreen) ?? terminals[0] ?? "DCT") : terminals[0] ?? "DCT";
  const filteredScreens = useMemo(() => myScreens.filter((screen) => screen.startsWith(activeTerm) && !screen.includes("YT")), [myScreens, activeTerm]);
  const handleLogin = async (event: React.FormEvent) => { event.preventDefault(); setLoginError(null); setSubmitting(true); const error = await login(username, password); if (error) setLoginError(error); else { setUsername(""); setPassword(""); } setSubmitting(false); };
  const timeStr = clock.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" });
  const dateStr = clock.toLocaleDateString("en-GB", { weekday: "short", day: "2-digit", month: "short" }).toUpperCase();

  return <header className="relative z-50 flex min-h-20 shrink-0 items-center justify-between border-b border-[var(--line)] bg-[rgba(5,3,13,.94)] px-5 shadow-depth-2 scanlines">
    <div className="flex min-w-0 items-center gap-5"><div className="flex items-center gap-3 border-r border-[var(--line)] pr-5"><div aria-hidden="true" className="corner-cut relative flex size-10 items-center justify-center border border-[var(--cyan)] bg-[var(--cyan)]/[0.08] glow-cyan"><span className="absolute h-5 w-px bg-[var(--cyan)]" /><span className="absolute h-px w-5 bg-[var(--cyan)]" /><span className="absolute bottom-2 size-1.5 rounded-full bg-[var(--pink)] shadow-[0_0_10px_var(--pink)]" /></div><div className="leading-none"><div className="text-[12px] font-black tracking-[0.2em] text-[var(--text-bright)]">CONTROL//ROOM</div><div className="mt-2 font-mono text-[8px] tracking-[0.2em] text-[var(--text-dim)]">PORT OS <span className="text-[var(--pink)]">●</span> UPLINK ACTIVE</div></div></div>{user && <div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.18em] text-[var(--text-secondary)]"><span className="status-dot size-1.5 rounded-full bg-[var(--green)]" />{activeTerm} NODE</div>}</div>
    {user ? <nav aria-label="Monitor navigation" className="absolute left-1/2 flex -translate-x-1/2 items-center gap-1">{filteredScreens.map((key) => <button key={key} onClick={() => onNavigate(key)} className={`corner-cut px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.1em] transition-all ${activeScreen === key ? "bg-[var(--pink)] text-[var(--bg-void)] shadow-[0_0_18px_rgba(255,45,183,.4)]" : "text-[var(--text-dim)] hover:bg-[var(--purple)]/10 hover:text-[var(--cyan)]"}`}>{SCREEN_LABELS[key] ?? key}</button>)}</nav> : <div className="hidden font-mono text-[9px] uppercase tracking-[0.2em] text-[var(--text-dim)] md:block">Secure control interface / unauthorized access monitored</div>}
    <div className="flex items-center gap-3"><div className="text-right font-mono leading-none"><div className="text-[14px] font-bold tabular-nums text-[var(--cyan)]">{timeStr}</div><div className="mt-1.5 text-[8px] tracking-[0.16em] text-[var(--text-dim)]">{dateStr} // ZULU</div></div>{user ? <><div className="h-8 w-px bg-[var(--line)]" /><div className="flex size-8 items-center justify-center border border-[var(--pink)] bg-[var(--pink)]/10 text-[11px] font-bold text-[var(--pink)]">{user.full_name?.charAt(0) ?? "U"}</div><button onClick={logout} className="corner-cut border border-[var(--red)]/60 px-3 py-2 font-mono text-[9px] font-bold uppercase tracking-[0.15em] text-[var(--red)] hover:bg-[var(--red)]/10">DISCONNECT</button></> : <form onSubmit={handleLogin} className="flex items-center gap-2">{loginError && <span className="max-w-[110px] truncate font-mono text-[9px] text-[var(--red)]">{loginError}</span>}<input aria-label="Username" placeholder="USER ID" value={username} onChange={(event) => setUsername(event.target.value)} className="h-8 w-24 border border-[var(--line)] bg-[var(--bg-surface)] px-2 font-mono text-[10px] text-[var(--text-bright)] placeholder:text-[var(--text-dim)] focus:border-[var(--cyan)] focus:outline-none" autoComplete="username" disabled={submitting} /><input aria-label="Password" type="password" placeholder="PASSCODE" value={password} onChange={(event) => setPassword(event.target.value)} className="h-8 w-24 border border-[var(--line)] bg-[var(--bg-surface)] px-2 font-mono text-[10px] text-[var(--text-bright)] placeholder:text-[var(--text-dim)] focus:border-[var(--cyan)] focus:outline-none" autoComplete="current-password" disabled={submitting} /><button type="submit" disabled={submitting || !username || !password} className="corner-cut h-8 bg-[var(--cyan)] px-3 font-mono text-[10px] font-bold tracking-[0.1em] text-[var(--bg-void)] hover:bg-[var(--pink)] disabled:opacity-30">{submitting ? "..." : "CONNECT"}</button></form>}</div>
  </header>;
}
